azure:
  storageAccount: ""
  storageAccountKey: ""
  storageContainer: ""
  # Valid environments AzureGlobal, AzureChinaCloud, AzureGermanCloud, AzureUSGovernment
  environment: "AzureGlobal"

clf:
  infrastructure: true
  application: true
  audit: false # NOTE: Enabling audit logs requires additional permissions

lokiStack:
  storageClassName: managed-csi
