apiVersion: v2
name: grafana-cr
description: A Helm chart for Deploying Grafana instances using the Grafana Operator

type: application

version: 0.1.1

home: https://github.com/rh-mobb/helm-charts

maintainers:
  - name: paulczar
