apiVersion: v2
name: aro-thanos-af
description: A Helm chart for Kubernetes
type: application
version: 0.6.0
dependencies:
  - name: grafana-cr
    version: "0.3.0"
    repository: "https://rh-mobb.github.io/helm-charts/"
    # repository: file://../grafana-cr
home: "https://rh-mobb.github.io/helm-charts/"
maintainers:
  - name: rh-mobb
