apiVersion: v2
name: aro-thanos-af
description: A Helm chart for Kubernetes
type: application
version: 0.8.5
dependencies:
  - name: grafana-cr
    version: "0.5.6"
    repository: "https://scorpiion.github.io/helm-charts/"
home: "https://rh-mobb.github.io/helm-charts/"
maintainers:
  - name: rh-mobb
