---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-gateway
  labels:
    app: thanos-store-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store-gateway
  serviceName: thanos-store-gateway
  template:
    metadata:
      labels:
        app: thanos-store-gateway
        thanos-store-api: "true"
    spec:
      serviceAccountName: {{ include "rosa-thanos-s3.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: thanos
        image: quay.io/thanos/thanos:v0.24.0-rc.2
        args:
        - store
        - --data-dir=/data
        - --index-cache-size=500MB
        - --chunk-pool-size=500MB
        - --objstore.config-file=/etc/prometheus/store-secret.yaml
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "200m"
            memory: 256Mi
        volumeMounts:
        - name: store-credentials
          mountPath: /etc/prometheus/
          readOnly: true
        - name: data
          mountPath: /data
      volumes:
      - name: store-credentials
        secret:
          secretName: store-credentials
      - name: data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-store-gateway
  name: thanos-store-gateway
spec:
  ports:
  - port: 10901
    protocol: TCP
    targetPort: grpc
    name: grpc
  selector:
    app: thanos-store-gateway
  type: ClusterIP
