apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  serviceAccount:
    name: logging-collector
  outputs:
  - name: lokistack-out
    type: lokiStack
    lokiStack:
      target:
        name: logging-loki
        namespace: openshift-logging
      authentication:
        token:
          from: serviceAccount
    tls:
      ca:
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
  pipelines:
  - name: all-to-default
    inputRefs:
    {{ if .Values.clf.infrastructure }}
    - infrastructure
    {{ end }}
    {{ if .Values.clf.application }}
    - application
    {{ end }}
    {{ if .Values.clf.audit }}
    - audit
    {{ end }}
    outputRefs:
    - lokistack-out
