apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  serviceAccount:
    name: cluster-logging-operator
  outputs:
    type: lokistack
    name: logging-loki
  pipelines:
  - name: all-to-default
    inputRefs:
    {{ if .Values.clf.infrastructure }}
    - infrastructure
    {{ end }}
    {{ if .Values.clf.application }}
    - application
    {{ end }}
    {{ if .Values.clf.audit }}
    - audit
    {{ end }}
    outputRefs:
    - default
