{{- $cluster := lookup "aro.openshift.io/v1alpha1" "Cluster" "" "cluster" -}}
{{- if (empty $cluster.spec) -}}
{{- $_ := set $cluster "spec" .Values.clusterSpec }}
{{- end -}}
{{- $machineSetName := printf "%s-worker-%s" $cluster.spec.infraId $cluster.spec.location -}}
{{- $machineSetName1 := printf "%s1" $machineSetName -}}

{{- $machineSetSpec := dict }}
{{- $machineSet := default (lookup "machine.openshift.io/v1beta1" "MachineSet" "openshift-machine-api" $machineSetName) (lookup "machine.openshift.io/v1beta1" "MachineSet" "openshift-machine-api" $machineSetName1) -}}
{{- if (empty $machineSet.spec) -}}
{{- $_ := deepCopy .Values.machineSetSpec | merge $machineSetSpec -}}
{{- else -}}
{{- $providerSpecValue := $machineSet.spec.template.spec.providerSpec.value -}}
{{- $_ := deepCopy $providerSpecValue | merge $machineSetSpec -}}
{{- end -}}
{{ $name := include "aro-machinesets.fullname" . }}
{{ range untilStep 1 (add (.Values.zoneCount | int) (1|int) | int) 1 }}
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ $cluster.spec.infraId }}
    machine.openshift.io/cluster-api-machine-role: {{ $.Values.machineRole }}
    machine.openshift.io/cluster-api-machine-type: {{ $.Values.machineRole }}
    machine.openshift.io/cluster-api-machineset: {{ $cluster.spec.infraId }}-{{ $cluster.spec.location }}-{{ . }}
  name: {{ $cluster.spec.infraId }}-{{ $name }}-{{ $cluster.spec.location }}-{{ . }}
  namespace: openshift-machine-api
spec:
  replicas: {{ $.Values.replicasPerZone }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ $cluster.spec.infraId }}
      machine.openshift.io/cluster-api-machineset: {{ $cluster.spec.infraId }}-{{ $cluster.spec.location }}-{{ . }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ $cluster.spec.infraId }}
        machine.openshift.io/cluster-api-machine-role: {{ $.Values.machineRole }}
        machine.openshift.io/cluster-api-machine-type: {{ $.Values.machineRole }}
        machine.openshift.io/cluster-api-machineset: {{ $cluster.spec.infraId }}-{{ $cluster.spec.location }}-{{ . }}
    spec:
      lifecycleHooks: {}
      metadata:
        labels: {{ $.Values.machineLabels | toYaml | nindent 10 }}
      taints: {{ $.Values.machineTaints | toYaml | nindent 8 }}
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image: {{ $machineSetSpec.image | toYaml | nindent 12 }}
          kind: AzureMachineProviderSpec
          location: {{ $machineSetSpec.location}}
          networkResourceGroup: {{ $machineSetSpec.networkResourceGroup }}
          osDisk: {{ $machineSetSpec.osDisk | toYaml | nindent 12 }}
          publicIP: {{ $machineSetSpec.publicIP }}
          publicLoadBalancer: {{ $machineSetSpec.publicLoadBalancer }}
          resourceGroup: {{ $machineSetSpec.resourceGroup }}
          subnet: {{ $machineSetSpec.subnet }}
          userDataSecret:
            name: worker-user-data
          vmSize: {{ $.Values.vmSize }}
          vnet: {{ $machineSetSpec.vnet }}
          zone: "{{ . }}"
{{- end }}
