---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-receive
  labels:
    app: thanos-receive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app: thanos-receive
    spec:
      serviceAccountName: {{ include "aro-thanos-af.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: thanos-receive
        image: quay.io/thanos/thanos:v0.24.0-rc.2
        args:
        - receive
        - --tsdb.path=/data/remote-write-receive-data
        - --debug.name=receive
        - --log.level=debug
        - --grpc-address=0.0.0.0:19891
        - --http-address=0.0.0.0:18091
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/prometheus/store-secret.yaml
        - --label
        - 'cluster="{{ .Values.rosa.clusterName }}"'
        ports:
        - name: http
          containerPort: 19291
        - name: grpc
          containerPort: 19891
        volumeMounts:
        - name: store-credentials
          mountPath: /etc/prometheus/
          readOnly: true
        - name: remote-write-data
          mountPath: /data/remote-write-receive-data
      volumes:
      - name: store-credentials
        secret:
          secretName: {{ include "aro-thanos-af.serviceAccountName" . }}-af-creds
      - name: remote-write-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: thanos-receive-tls
  labels:
    app: thanos-receive
  name: thanos-receive
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: http
    name: http
  - port: 19891
    protocol: TCP
    targetPort: grpc
    name: grpc
  selector:
    app: thanos-receive
  type: ClusterIP
