{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aro-thanos-af.serviceAccountName" . }}
  labels:
    {{- include "aro-thanos-af.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  type: kubernetes.io/service-account-token
  annotations:
    kubernetes.io/service-account.name: {{ include "aro-thanos-af.serviceAccountName" . }}
  name: {{ include "aro-thanos-af.serviceAccountName" . }}-token
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: {{ include "aro-thanos-af.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
