apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocp-proxy-api.fullname" . }}-config
  labels:
    {{- include "ocp-proxy-api.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes auto;
    error_log /dev/stdout info;

    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log   /dev/stdout main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        # include             /etc/nginx/mime.types;
        default_type        application/octet-stream;
    }

    stream {
        map_hash_bucket_size 256;
        map $ssl_preread_server_name $name {
          api.{{ .Values.ocp.clusterDomain }} api_backend;
          default ingress_backend;
        }
        upstream api_backend {
          server apiserver.openshift-kube-apiserver:443;
          {{ if .Values.keepalive.enabled -}}
          keepalive {{ .Values.keepalive.connections }};
          {{- end }}
        }
        upstream ingress_backend {
          server {{ .Values.ocp.ingressLB }}:443;
          {{ if .Values.keepalive.enabled -}}
          keepalive {{ .Values.keepalive.connections }};
          {{- end }}
        }

        server {
            listen       6443;
            # Allow List
            {{- range .Values.acls.allow }}
            allow {{ . }};
            {{- end }}
            # Deny List
            {{- range .Values.acls.deny }}
            deny {{ . }};
            {{- end }}
            {{- if .Values.acls.defaultDeny }}
            # Default Deny
            deny all;
            {{- end }}

            proxy_pass   $name;
            
            {{ if .Values.keepalive.enabled -}}
            # Setting these keepalive parameters based on official docs.
            # This avoids closing each connection and hence avoids exhausting the available resources
            # https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive
            #   and here:
            # https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#no-keepalives
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            {{- end }}

            ssl_preread on;
        }
    }
