apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
  labels:
    {{- include "aro-clf-blob.labels" . | nindent 4 }}
spec:
  size: 1x.pico
  storage:
    schemas:
    - version: v13
      effectiveDate: 2025-11-02
    secret:
      name: logging-loki-azure
      type: azure
  storageClassName: {{ .Values.lokiStack.storageClassName }}
  tenants:
    mode: openshift-logging
