apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-collector
  namespace: openshift-logging
---


# TODO: Automate these
# oc adm policy add-cluster-role-to-user logging-collector-logs-writer -z logging-collector -n openshift-logging
# oc adm policy add-cluster-role-to-user collect-application-logs -z logging-collector -n openshift-logging
# oc adm policy add-cluster-role-to-user collect-audit-logs -z logging-collector -n openshift-logging
# oc adm policy add-cluster-role-to-user collect-infrastructure-log -z logging-collector -n openshift-logging
