apiVersion: v2
name: ocp-proxy-api
description: A Helm chart for Kubernetes to create and manage an nginx proxy for OCP API/Console
type: application
version: 0.2.0
home: "https://rh-mobb.github.io/helm-charts/"
maintainers:
  - name: rh-mobb
