kind: ConfigMap
metadata:
  name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
  labels:
    {{- include "aro-thanos-af.labels" . | nindent 4 }}
apiVersion: v1
data:
  agent.yaml: |
    server:
      log_level: debug
    integrations:
      agent:
        enabled: true
    metrics:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 15s
        external_labels:
          cluster: {{ .Values.rosa.clusterName }}
        remote_write:
          - url: "http://thanos-receive.{{ .Release.Namespace }}.svc.cluster.local:9091/api/v1/receive"
            queue_config:
              max_samples_per_send: 1000
              max_shards: 200
              capacity: 2500
      configs:
        - name: default
          scrape_configs:
            - job_name: cluster-monitoring
              honor_labels: true
              params:
                'match[]':
                - '{job!=""}'
              scrape_interval: 30s
              scrape_timeout: 30s
              metrics_path: /federate
              scheme: https
              static_configs:
                - targets: ['prometheus-k8s.openshift-monitoring:9091']
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                insecure_skip_verify: true
