apiVersion: v2
name: aro-pull-secret
description: A Helm chart configuring a pull secret for the Aro cluster.
maintainers:
  - name: paulczar
home: https://github.com/rh-mobb/helm-charts
type: application
version: 0.1.1
